# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_plain_textkhjk = QtWidgets.QLabel(self.centralwidget)
        self.txt_plain_textkhjk.setGeometry(QtCore.QRect(30, 120, 47, 13))
        self.txt_plain_textkhjk.setObjectName("txt_plain_textkhjk")
        self.txt_cipher_text1 = QtWidgets.QLabel(self.centralwidget)
        self.txt_cipher_text1.setGeometry(QtCore.QRect(20, 280, 61, 16))
        self.txt_cipher_text1.setObjectName("txt_cipher_text1")
        self.txt_info1 = QtWidgets.QLabel(self.centralwidget)
        self.txt_info1.setGeometry(QtCore.QRect(380, 130, 61, 16))
        self.txt_info1.setObjectName("txt_info1")
        self.txt_sign1 = QtWidgets.QLabel(self.centralwidget)
        self.txt_sign1.setGeometry(QtCore.QRect(380, 290, 47, 13))
        self.txt_sign1.setObjectName("txt_sign1")
        self.btn_gen_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_keys.setGeometry(QtCore.QRect(470, 50, 101, 23))
        self.btn_gen_keys.setObjectName("btn_gen_keys")
        self.btn_encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_encrypt.setGeometry(QtCore.QRect(80, 390, 75, 23))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(240, 390, 75, 23))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(470, 390, 75, 23))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_virify = QtWidgets.QPushButton(self.centralwidget)
        self.btn_virify.setGeometry(QtCore.QRect(620, 390, 75, 23))
        self.btn_virify.setObjectName("btn_virify")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 40, 81, 41))
        self.label_5.setObjectName("label_5")
        self.txt_plain_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_plain_text.setGeometry(QtCore.QRect(100, 110, 241, 71))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.txt_cipher_text = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_cipher_text.setGeometry(QtCore.QRect(90, 260, 241, 71))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.txt_info = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_info.setGeometry(QtCore.QRect(480, 110, 241, 71))
        self.txt_info.setObjectName("txt_info")
        self.txt_sign = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sign.setGeometry(QtCore.QRect(480, 270, 241, 71))
        self.txt_sign.setObjectName("txt_sign")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.txt_plain_textkhjk.setText(_translate("MainWindow", "Plain Text"))
        self.txt_cipher_text1.setText(_translate("MainWindow", "Cipher Text"))
        self.txt_info1.setText(_translate("MainWindow", "Information"))
        self.txt_sign1.setText(_translate("MainWindow", "Signature"))
        self.btn_gen_keys.setText(_translate("MainWindow", "Generate Keys"))
        self.btn_encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.btn_virify.setText(_translate("MainWindow", "Verify"))
        self.label_5.setText(_translate("MainWindow", "RSA CIPHER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
